### ISSUE TITLE
[NoBrainer] Profiling error: ArgumentError comparison of Symbol with 0 failed

### ISSUE THREAD

**Issue by 34code** [NoBrainerORM/devise-nobrainer#8]
I keep getting this in my logs when accessing any of the methods involving user authentication with devise (e.g. login/logout/edit-profile) .. I've also noticed that the `current_user` helper method from devise causes this to appear in the logs. 

As I don't experience any user level problems -- I'm not super concerned, but am wondering if the presence of this message:

`[NoBrainer] Profiling error: ArgumentError comparison of Symbol with 0 failed` 

means that the app is running slower than it can?

**Comment by nviennot** [comment]
This message is coming from https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/query_runner/profiler.rb#L32
you can add a `puts e.backtrace` so we can see where the exception is coming from.
The only place I can see this happening is from https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/profiler/logger.rb#L9
If `NoBrainer.logger.level` is a symbol and not an number, that can be a problem. What do you have?

**Comment by 34code** [comment]
heres what I got:

```
09:05:47 http.1  | [NoBrainer] Profiling error: ArgumentError comparison of Symbol with 0 failed
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/profiler/logger.rb:9:in `>'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/profiler/logger.rb:9:in `on_query'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/profiler.rb:30:in `block in profiler_end'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/profiler.rb:28:in `each'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/profiler.rb:28:in `profiler_end'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/profiler.rb:4:in `block in call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/profiler.rb:4:in `tap'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/profiler.rb:4:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/table_on_demand.rb:3:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/database_on_demand.rb:3:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/missing_index.rb:3:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner/run_options.rb:48:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/query_runner.rb:21:in `run'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/nobrainer.rb:26:in `run'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/criteria/run.rb:16:in `run'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/criteria/run.rb:12:in `run'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/criteria/first.rb:29:in `get_one'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/criteria/eager_load.rb:43:in `get_one'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/criteria/first.rb:5:in `first'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/criteria/cache.rb:64:in `block (2 levels) in use_cache_for'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/criteria/find.rb:11:in `find?'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/document/criteria.rb:16:in `find?'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/devise-nobrainer-0.5.0/lib/orm_adapter/adapters/nobrainer.rb:23:in `get'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/devise-4.3.0/lib/devise/models/authenticatable.rb:229:in `serialize_from_session'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/devise-4.3.0/lib/devise.rb:478:in `block (2 levels) in configure_warden!'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/warden-1.2.7/lib/warden/session_serializer.rb:35:in `fetch'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/warden-1.2.7/lib/warden/proxy.rb:213:in `user'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/warden-1.2.7/lib/warden/proxy.rb:323:in `_perform_authentication'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/warden-1.2.7/lib/warden/proxy.rb:105:in `authenticate'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/devise-4.3.0/lib/devise/controllers/helpers.rb:124:in `current_user'
09:05:47 http.1  | /Users/sambit/Documents/Projects/RAILS/Staging/alpha-shome/app/controllers/info_pages_controller.rb:21:in `home'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in `process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/nobrainer-0.33.0/lib/no_brainer/profiler/controller_runtime.rb:44:in `process_action'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in `process'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionview-5.1.4/lib/action_view/rendering.rb:30:in `process'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal.rb:189:in `dispatch'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_controller/metal.rb:253:in `dispatch'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:31:in `serve'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `each'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `serve'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rollbar-2.15.5/lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rollbar-2.15.5/lib/rollbar.rb:145:in `scoped'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rollbar-2.15.5/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rollbar-2.15.5/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/web-console-3.5.1/lib/web_console/middleware.rb:135:in `call_app'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/web-console-3.5.1/lib/web_console/middleware.rb:28:in `block in call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `catch'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rails_semantic_logger-4.1.3/lib/rails_semantic_logger/extensions/rails/rack/logger.rb:21:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/google-cloud-trace-0.28.1/lib/google/cloud/trace/middleware.rb:156:in `block in call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/google-cloud-trace-0.28.1/lib/google/cloud/trace.rb:341:in `block in in_span'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/google-cloud-trace-0.28.1/lib/google/cloud/trace/trace_record.rb:231:in `in_span'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/google-cloud-trace-0.28.1/lib/google/cloud/trace.rb:338:in `in_span'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/google-cloud-trace-0.28.1/lib/google/cloud/trace/middleware.rb:154:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/actionpack-5.1.4/lib/action_dispatch/middleware/static.rb:125:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/webpacker-3.2.0/lib/webpacker/dev_server_proxy.rb:18:in `perform_request'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-proxy-0.6.3/lib/rack/proxy.rb:57:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
09:05:47 http.1  | /Users/sambit/.gem/ruby/2.4.2/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

there seems to be another nobrainer profiler file its referencing..

**Comment by 34code** [comment]
How can I check if `NoBrainer.logger.level` is a symbol?

**Comment by 34code** [comment]
update:

I did a `puts NoBrainer.logger.level.class` under `e.backtrace` and it does indeed say `Symbol`

**Comment by 34code** [comment]
`Nobrainer.logger.level = :debug` I believe

**Comment by 34code** [comment]
I set `Nobrainer.logger.level` to `Logger.new(STDERR)` and that fixed it.. 

It was set to `config.default_logger` and that was giving me some issues..
